[package]
name = "suger-bullet"
version = "0.1.0"
authors = ["lilybrevec <allabrevec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
irc = { git = "https://github.com/lilybrevec/irc", branch = "0.14", features = ["ctcp", "toml"] }
futures = "0.3.4"
tokio = "0.2.17"
failure = "0.1.1"